### ISSUE TITLE
Search as per your example

### ISSUE THREAD

**Issue by jeromeof** [aesy/musicbrainz-api-client#3]
Hi,
  Just curious about your project. But I can't seem to find the search methods? e.g. 

 client.artist.search("Peter Gabriel")

I can find the browse and the lookup but no search?

Thanks

**Comment by aesy** [comment]
Hey,

You're right, the readme is incorrect. It was mostly written to show what's to come rather than what's actually implemented. I've updated the readme to reflect the current state of the project and [pushed a branch](https://github.com/aesy/musicbrainz-api-client/tree/search-requests) with the current state of search requests.

**Comment by aesy** [comment]
Closing as the docs are now correct. Search requests will be supported at some point, but I can't say when.
